plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.fx'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    querydsl.extendsFrom compileClasspath
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Mongo
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

    //redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    //redis session
    implementation 'org.springframework.session:spring-session-data-redis'

    //kafka
    implementation 'org.springframework.kafka:spring-kafka'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

    //Netflix eureka client
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:4.2.0'

    // QueryDSL
    implementation("com.querydsl:querydsl-mongodb:5.0.0") {
        exclude group: "org.mongodb", module: "mongo-java-driver"
    }
    implementation 'com.querydsl:querydsl-core:5.0.0'
    annotationProcessor 'com.querydsl:querydsl-apt:5.0.0'
    annotationProcessor 'org.springframework.boot:spring-boot-starter-data-mongodb'

    implementation project(":global")
    implementation project(":file")
}

// 컴파일러 옵션에 annotationProcessor 직접 지정
compileJava {
    options.compilerArgs += [
            "-processor", 'lombok.launch.AnnotationProcessorHider$AnnotationProcessor,org.springframework.data.mongodb.repository.support.MongoAnnotationProcessor'
    ]
}

tasks.named('test') {
    useJUnitPlatform()
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}
