server:
  port: ${ARTICLE_PORT}

spring:
  application:
    name: baobab-article

  jpa:
    show-sql: true

  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${MONGO_DATABASE}

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_URL}
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_URL}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

# logging
logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate: ERROR

log:
  config:
    path: ${LOG_CONFIG_PATH}

url:
  scheme: ${FILE_URL_SCHEME}
  host: ${FILE_URL_HOST}
  path:
    article: ${FILE_PATH_ARTICLE}
    user: ${FILE_PATH_USER}

cipher:
  key: ${CIPHER_KEY}