server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id : baobab-article
          uri : lb://BAOBAB-ARTICLE
          predicates:
            - Path=/article-service/**
          filters:
            - RewritePath=/article-service/(open-api|api)/(?<segment>.*), /$\{segment}

        - id: baobab-users
          uri: lb://BAOBAB-USERS
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(open-api|api)/(?<segment>.*), /$\{segment}

# logging
logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate: ERROR

log:
  config:
    path: logs

token:
  validation:
    url: http://localhost:8000/user-service/open-api/validation