server:
  port: ${EUREKA_PORT}

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false # default : true
    fetch-registry: false # default : true

# logging
logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate: ERROR

log:
  config:
    path: ${LOG_CONFIG_PATH}

management:
  endpoints:
    web:
      exposure:
        include: prometheus