plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.fx'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // kafka
    implementation 'org.springframework.kafka:spring-kafka'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

    // mongodb
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

    // mockito
    testImplementation 'org.mockito:mockito-core:4.11.0'
    testImplementation 'org.mockito:mockito-inline:4.11.0'

    //Netflix eureka client
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:4.2.0'
    implementation 'com.thoughtworks.xstream:xstream:1.4.21'
    implementation 'org.apache.httpcomponents:httpclient:4.5.13'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Aop
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    implementation project(":global")

}

tasks.named('test') {
    useJUnitPlatform()
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}
